enpitut2018/VideoSocialBookmarkFrontend

src/components/organisms/CommentSubmitForm.js
src/components/templates/Thread.js

Add Comment to ThreadPage

---

src/assets/images/material-icon/baseline-error-24px.svg
src/assets/images/material-icon/baseline-error_outline-24px.svg
src/assets/images/material-icon/baseline-exit_to_app-24px.svg
src/assets/images/material-icon/baseline-person-24px.svg
src/components/molecules/DropdownMenuItem.js
src/components/organisms/DropdownMenu.js
src/components/organisms/Header.js
src/theme/colors.json
src/theme/shadows.js

Update Header Design

---

src/Routes.js
src/actions/UserActions.js
src/components/molecules/UserBookmarkItem.js
src/components/organisms/UserBookmark.js
src/components/pages/User.js
src/components/templates/User.js
src/reducers/user.js

backend: https://github.com/enpitut2018/VideoSocialBookmark/pull/47/files

ユーザーのブックマーク表示ページを作成

---

src/actions/CommentActions.js

**概要**
postCommentするとき
```
{
content: comment
}
```
だったのを
```
{
comment: {
content: comment
}
}
```
に変更
**変更内容**
**補足(option)**

Fix postComment

---

src/components/atoms/Text.js
src/components/molecules/EntryTop.js
src/components/molecules/TrendItem.js
src/components/organisms/Footer.js

**概要**
**変更内容**
**補足(option)**

fix design

---

src/components/molecules/EntryTop.js

**概要**
Entryページのデザイン修正
**変更内容**
**補足(option)**

fix entry page design

---

src/components/atoms/AnkerStyle.js
src/components/atoms/Text.js
src/components/atoms/TextArea.js
src/components/atoms/TextInput.js
src/components/atoms/Wrapper.js
src/components/molecules/TrendItem.js
src/components/organisms/DropdownMenu.js
src/components/organisms/Header.js
src/components/organisms/Trend.js
src/components/organisms/URLSubmitForm.js
src/theme/colors.json

**概要**
**変更内容**
**補足(option)**

fix form and dropdownmenu

---

src/components/templates/Login.js
src/components/templates/Registration.js

**概要**
ログインフォームと登録フォーム修正
**変更内容**
**補足(option)**

fix login and registration

---

.gitmodules
package.json
src/App.js
src/App.test.js
src/actions/BookmarkActions.js
src/actions/TrendActions.js
src/components/atoms/Button.js
src/components/atoms/Text.js
src/components/molecules/BookmarkButton.js
src/components/molecules/TrendItem.js
src/components/organisms/CommentSubmitForm.js
src/components/organisms/Trend.js
src/components/organisms/URLSubmitForm.js
src/components/organisms/UserBookmarks.js
src/components/templates/User.js
src/reducers/bookmarks.js
src/reducers/index.js
src/reducers/trend.js
src/theme/colors.json
src/theme/shadows.js
yarn.lock

**概要**
**変更内容**
**補足(option)**

Add bookmark button

---

src/Routes.js
src/actions/PlaylistActions.js
src/components/molecules/PlaylistItem.js
src/components/organisms/PlaylistWrapper.js
src/components/pages/Playlist.js
src/components/templates/Playlist.js

[add] プレイリスト表示ページの実装

---

.stylelintrc
.travis.yml
package.json
src/components/organisms/Footer.js
src/components/organisms/Header.js
src/privacy.js
src/reducers/bookmarks.js
yarn.lock

[dev] Add lint

---

src/components/organisms/UserBookmarks.js
src/components/templates/User.js

typo Fixed #143

---

src/components/molecules/TrendItem.js

Fit video size at trend

---

src/components/templates/Registration.js
src/redux-token-auth-config.js

**概要**
ユーザーがnonameの問題
**変更内容**
最初の登録でユーザー名を追加できるようにした。
**補足(option)**
コメント欄の部分ではまだnoname

ユーザー名のフォームの追加

---

src/components/atoms/Embed.js

Fix embed null

---

src/components/atoms/Embed.js
src/components/atoms/Thumbnail.js
src/components/molecules/PlaylistItem.js
src/components/molecules/TrendItem.js
src/components/molecules/UserBookmarkItem.js
src/components/organisms/SNSShareForm.js

ニコ動のサムネイルが見れない問題を修正

---

src/Routes.js
src/actions/SearchActions.js
src/components/organisms/Header.js
src/components/pages/Search.js
src/components/templates/Search.js
src/reducers/index.js
src/reducers/search.js

**概要**
#114 
**変更内容**
**補足(option)**

Solved #114 検索を実装

---

src/components/molecules/DropdownMenuItem.js
src/components/molecules/DropdownPlaylistMenuItem.js
src/components/organisms/DropdownMyMenu.js
src/components/organisms/DropdownPlaylistMenu.js

fix dropdownmenu padding

---

src/components/atoms/UserIcon.js
src/components/molecules/EntryItem.js

Display user icon at comments

---

src/components/molecules/UserBookmarkItem.js

Display comment at mypage bookmarks

Display comment at mypage bookmarks

---

src/actions/PlaylistActions.js
src/components/molecules/PlaylistOverviewItem.js
src/components/organisms/Playlists.js
src/components/templates/User.js
src/reducers/playlists.js

Show playlist at user page

---

src/actions/SearchActions.js
src/components/pages/Search.js
src/components/templates/Search.js
src/reducers/search.js

Add pagination to search

---

src/components/organisms/DropdownPlaylistMenu.js
src/components/organisms/PlaylistOverview.js
src/components/organisms/PlaylistWrapper.js

**概要**
**変更内容**
**補足(option)**

プレイリストの順番を修正

---

src/help.js

**概要**
**変更内容**
**補足(option)**

helpページのリンクを飛べるようにした

---

src/actions/TrendActions.js
src/components/organisms/Pagination.js
src/components/organisms/Trend.js

**概要**
トレンドのページn目で更新したときに，ページ番号を維持
**変更内容**
**補足(option)**

fix pagenation

---

src/actions/PlaylistActions.js
src/assets/images/material-icon/baseline-delete-24px.svg.js
src/assets/images/material-icon/baseline-more_vert-24px.svg.js
src/components/molecules/DropdownMenuItem.js
src/components/molecules/Embed.js
src/components/organisms/DropdownMyMenu.js
src/components/organisms/DropdownPlyalistMoreMenu.js
src/components/organisms/PlaylistOverview.js
src/components/organisms/Playlists.js

**概要**
**変更内容**
**補足(option)**

プレイリストを削除できるようにした

---

src/components/molecules/Form.js
src/components/molecules/TrendItem.js
src/components/organisms/DropwodnUploadForm.js
src/components/organisms/SearchForm.js

**概要**
**変更内容**
**補足(option)**

トップページをスマホで開いても崩れないようにした

---

src/components/molecules/LabeledInput.js
src/components/organisms/URLSubmitForm.js
src/components/templates/Login.js
src/components/templates/Registration.js
src/reducers/entries.tsx

**概要**
**変更内容**
**補足(option)**

フォームのラベル動作修正　

---

src/actions/PlaylistActions.js
src/components/atoms/Text.js
src/components/molecules/BookmarkButton.js
src/components/organisms/DropdownPlyalistMoreMenu.js
src/components/organisms/PlaylistOverview.js
src/components/organisms/Playlists.js
src/components/organisms/ToastManager.js
src/components/templates/MyPage.js
src/components/templates/User.js
src/reducers/playlists.tsx

**概要**
**変更内容**
**補足(option)**

他人のプレイリストを保存できるようにする
